name: Teste de Carga com K6

on:
  workflow_dispatch:

jobs:
  k6:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Homebrew e K6
        run: |
          sudo apt update
          sudo apt install -y curl
          curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.profile
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install k6

      - name: Executar teste de carga
        run: k6 run teste-buscape.js

